class Exercise {
  final String exerciseId,
      exerciseName,
      exerciseSetRepeat,
      exercisePic,
      exerciseZone,
      exerciseDayofweek;

  Exercise(
      {this.exerciseId,
      this.exerciseName,
      this.exerciseSetRepeat,
      this.exercisePic,
      this.exerciseZone,
      this.exerciseDayofweek});
}

final exercises = [
  Exercise(
      exerciseId: "1",
      exerciseName: "Barbell Chest Press",
      exerciseSetRepeat: "4 Set - 10 Repeat",
      exercisePic: "assets/chest.jpg",
      exerciseZone: "Chest",
      exerciseDayofweek: "1"),
  Exercise(
      exerciseId: "2",
      exerciseName: "Dumbell Fly",
      exerciseSetRepeat: "3 Set - 15 Repeat",
      exercisePic: "assets/chest.jpg",
      exerciseZone: "Chest",
      exerciseDayofweek: "1"),
  Exercise(
      exerciseId: "3",
      exerciseName: "Pull-Up",
      exerciseSetRepeat: "4 Set - 10 Repeat",
      exercisePic: "assets/back1.jpg",
      exerciseZone: "Back",
      exerciseDayofweek: "1"),
  Exercise(
      exerciseId: "5",
      exerciseName: "Dumbbell Shoulder Press",
      exerciseSetRepeat:"4 Set - 12 Repeat",
      exercisePic: "assets/shoulder.jpg",
      exerciseZone: "Shoulder",
      exerciseDayofweek: "1"),
  Exercise(
      exerciseId: "7",
      exerciseName: "Dumbbell Curl",
      exerciseSetRepeat:"4 Set - 15 Repeat",
      exercisePic: "assets/arm.jpg",
      exerciseZone: "Arm",
      exerciseDayofweek: "1"),
  Exercise(
      exerciseId: "0",
      exerciseName: "Rest",
      exerciseSetRepeat:"1 Day",
      exercisePic: "assets/rest.png",
      exerciseZone: "",
      exerciseDayofweek: "1"),
  Exercise(
      exerciseId: "3",
      exerciseName: "Pull-Up",
      exerciseSetRepeat:"3 Set - 8 Repeat",
      exercisePic: "assets/back1.jpg",
      exerciseZone: "Back",
      exerciseDayofweek: "2"),
  Exercise(
      exerciseId: "4",
      exerciseName: "Lat Pull-Down",
      exerciseSetRepeat:"4 Set - 12 Repeat",
      exercisePic: "assets/back1.jpg",
      exerciseZone: "Back",
      exerciseDayofweek: "2"),
  Exercise(
      exerciseId: "5",
      exerciseName: "Dumbbell Shoulder Press",
      exerciseSetRepeat:"4 Set - 12 Repeat",
      exercisePic: "assets/shoulder.jpg",
      exerciseZone: "Shoulder",
      exerciseDayofweek: "3"),
  Exercise(
      exerciseId: "6",
      exerciseName: "Dumbbell Lateral Raise",
      exerciseSetRepeat:"4 Set - 15 Repeat",
      exercisePic: "assets/shoulder.jpg",
      exerciseZone: "Shoulder",
      exerciseDayofweek: "3"),
  Exercise(
      exerciseId: "7",
      exerciseName: "Dumbbell Curl",
      exerciseSetRepeat:"4 Set - 12 Repeat",
      exercisePic: "assets/arm.jpg",
      exerciseZone: "Arm",
      exerciseDayofweek: "4"),
  Exercise(
      exerciseId: "8",
      exerciseName: "Rope Pushdown",
      exerciseSetRepeat:"4 Set - 12 Repeat",
      exercisePic: "assets/arm.jpg",
      exerciseZone: "Arm",
      exerciseDayofweek: "4"),
  Exercise(
      exerciseId: "9",
      exerciseName: "Squat",
      exerciseSetRepeat:"3 Set - 15 Repeat",
      exercisePic: "assets/leg1.jpg",
      exerciseZone: "Leg",
      exerciseDayofweek: "5"),
  Exercise(
      exerciseId: "10",
      exerciseName: "Leg extension",
      exerciseSetRepeat:"4 Set - 10 Repeat",
      exercisePic: "assets/leg1.jpg",
      exerciseZone: "Leg",
      exerciseDayofweek: "5"),
  Exercise(
      exerciseId: "0",
      exerciseName: "Rest",
      exerciseSetRepeat:"1 Day",
      exercisePic: "assets/rest.png",
      exerciseZone: "",
      exerciseDayofweek: "6"),
  Exercise(
      exerciseId: "0",
      exerciseName: "Rest",
      exerciseSetRepeat:"1 Day",
      exercisePic: "assets/rest.png",
      exerciseZone: "",
      exerciseDayofweek: "7"),
];
