class UserExercises {
  final String exerciseId,
      exerciseName,
      exerciseSetRepeat,
      exercisePic,
      exerciseMuscle,
      exerciseMuscleId,
      exerciseDayofweek;

  UserExercises(
      {this.exerciseId,
      this.exerciseName,
      this.exerciseSetRepeat,
      this.exercisePic,
      this.exerciseMuscle,
      this.exerciseMuscleId,
      this.exerciseDayofweek});
}

final user_exercises = [
  UserExercises(
      exerciseId: "1",
      exerciseName: "Barbell Chest Press",
      exerciseSetRepeat: "4 Set - 10 Repeat",
      exercisePic: "assets/chest.jpg",
      exerciseMuscle: "Chest",
      exerciseMuscleId: "1",
      exerciseDayofweek: "1"),
  UserExercises(
      exerciseId: "2",
      exerciseName: "Dumbell Fly",
      exerciseSetRepeat: "3 Set - 15 Repeat",
      exercisePic: "assets/chest.jpg",
      exerciseMuscle: "Chest",
      exerciseMuscleId: "1",
      exerciseDayofweek: "1"),
  UserExercises(
      exerciseId: "3",
      exerciseName: "Pull-Up",
      exerciseSetRepeat: "4 Set - 10 Repeat",
      exercisePic: "assets/back1.jpg",
      exerciseMuscle: "Back",
      exerciseMuscleId: "2",
      exerciseDayofweek: "1"),
  UserExercises(
      exerciseId: "5",
      exerciseName: "Dumbbell Shoulder Press",
      exerciseSetRepeat: "4 Set - 12 Repeat",
      exercisePic: "assets/shoulder.jpg",
      exerciseMuscle: "Shoulder",
      exerciseMuscleId: "3",
      exerciseDayofweek: "1"),
  UserExercises(
      exerciseId: "7",
      exerciseName: "Dumbbell Curl",
      exerciseSetRepeat: "4 Set - 15 Repeat",
      exercisePic: "assets/biceps.jpg",
      exerciseMuscle: "Biceps",
      exerciseMuscleId: "4",
      exerciseDayofweek: "1"),
  UserExercises(
      exerciseId: "0",
      exerciseName: "Rest",
      exerciseSetRepeat: "1 Day",
      exercisePic: "assets/rest.png",
      exerciseMuscle: "",
      exerciseMuscleId: "0",
      exerciseDayofweek: "1"),
  UserExercises(
      exerciseId: "3",
      exerciseName: "Pull-Up",
      exerciseSetRepeat: "3 Set - 8 Repeat",
      exercisePic: "assets/back1.jpg",
      exerciseMuscle: "Back",
      exerciseMuscleId: "2",
      exerciseDayofweek: "2"),
  UserExercises(
      exerciseId: "4",
      exerciseName: "Lat Pull-Down",
      exerciseSetRepeat: "4 Set - 12 Repeat",
      exercisePic: "assets/back1.jpg",
      exerciseMuscle: "Back",
      exerciseMuscleId: "2",
      exerciseDayofweek: "2"),
  UserExercises(
      exerciseId: "5",
      exerciseName: "Dumbbell Shoulder Press",
      exerciseSetRepeat: "4 Set - 12 Repeat",
      exercisePic: "assets/shoulder.jpg",
      exerciseMuscle: "Shoulder",
      exerciseMuscleId: "3",
      exerciseDayofweek: "3"),
  UserExercises(
      exerciseId: "6",
      exerciseName: "Dumbbell Lateral Raise",
      exerciseSetRepeat: "4 Set - 15 Repeat",
      exercisePic: "assets/shoulder.jpg",
      exerciseMuscle: "Shoulder",
      exerciseMuscleId: "3",
      exerciseDayofweek: "3"),
  UserExercises(
      exerciseId: "7",
      exerciseName: "Dumbbell Curl",
      exerciseSetRepeat: "4 Set - 12 Repeat",
      exercisePic: "assets/triceps.jpg",
      exerciseMuscle: "Triceps",
      exerciseMuscleId: "5",
      exerciseDayofweek: "4"),
  UserExercises(
      exerciseId: "8",
      exerciseName: "Rope Pushdown",
      exerciseSetRepeat: "4 Set - 12 Repeat",
      exercisePic: "assets/triceps.jpg",
      exerciseMuscle: "Triceps",
      exerciseMuscleId: "5",
      exerciseDayofweek: "4"),
  UserExercises(
      exerciseId: "9",
      exerciseName: "Squat",
      exerciseSetRepeat: "3 Set - 15 Repeat",
      exercisePic: "assets/leg1.jpg",
      exerciseMuscle: "Leg",
      exerciseMuscleId: "6",
      exerciseDayofweek: "5"),
  UserExercises(
      exerciseId: "10",
      exerciseName: "Leg extension",
      exerciseSetRepeat: "4 Set - 10 Repeat",
      exercisePic: "assets/leg1.jpg",
      exerciseMuscle: "Leg",
      exerciseMuscleId: "6",
      exerciseDayofweek: "5"),
  UserExercises(
      exerciseId: "0",
      exerciseName: "Rest",
      exerciseSetRepeat: "1 Day",
      exercisePic: "assets/rest.png",
      exerciseMuscle: "",
      exerciseMuscleId: "0",
      exerciseDayofweek: "6"),
  UserExercises(
      exerciseId: "0",
      exerciseName: "Rest",
      exerciseSetRepeat: "1 Day",
      exercisePic: "assets/rest.png",
      exerciseMuscle: "",
      exerciseMuscleId: "0",
      exerciseDayofweek: "7"),
];
